name: 'terralink-checker'
description: 'Executes terralink check to verify your project is not dev loaded'
inputs:
  directory:
    description: 'Directory to check with terralink'
    required: false
    default: '${{ github.workspace }}'
  version:
    description: 'Terralink version to use (default: 0.3.1)' # x-release-please-version
    required: false
    default: '0.3.1' # x-release-please-version
runs:
  using: 'composite'
  steps:
    - name: Install terralink
      shell: bash
      run: ${{ github.action_path }}/install.sh "${{ inputs.version }}"
    - name: Run terralink check
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh "${{ inputs.directory }}"
